import type { Metadata } from "next";
/*

inter se refiere a una fuente personalizada importada de 
Google Fonts usando la funcionalidad específica de Next.js para gestionar fuentes.

Inter es una función proporcionada por Next.js para cargar y usar la fuente Inter desde Google Fonts. 
La función facilita la inclusión de fuentes personalizadas en una aplicación Next.js sin tener que preocuparse por los aspectos de rendimiento y carga de fuentes.

*/
import { Inter } from "next/font/google";
// next-themes es una mini library que ayuda a poner themes por medio de module css o tailwind
import { ThemeProvider } from "next-themes";
// Este global css solo contiene el archivo de configuracion de tailwind
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget } from "@/components/PopupWidget";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" >
          <Navbar />
          <div>{children}</div>
          <Footer />
          <PopupWidget />
        </ThemeProvider>
      </body>
    </html>
  );
}
